### ISSUE TITLE
DateTime precision

### ISSUE THREAD

**Issue by lsaenzt** [CalebDepatie/Julianda#6]
I am converting Oanda DateTime  to Julia DateTime objects. Julia onlye supports millisecond precision (vs nanosecond from Oanda) if the Date is included.

Other packages, like [TimesDates.jl](https://github.com/JeffreySarnoff/TimesDates.jl), provide nanoseconds. 

I'd rather stick to Base.dates as it should be more robust and milliseconds should be enough, but is something to discuss about.

**Comment by CalebDepatie** [comment]
Sticking to base.Dates is probably the most intuitive for other users and ensures that people using this library dont have to use an additional library to interact with it.
