### ISSUE TITLE
r.status != 200

### ISSUE THREAD

**Issue by lsaenzt** [CalebDepatie/Julianda#7]
After each HTTP request, these lines appear:

`    if r.status != 200
        println(r.status)
    end`

I think that they are never called as HTTP.request returns an error if the response is not 200. Right?

**Comment by CalebDepatie** [comment]
Ah yes, it throws the exception `HTTP.ExceptionRequest.StatusError` This is just me being used to golangs style of api interaction haha, I'll replace these with a try catch block possibly.
